[frontend]
vishnuv8.shop

[catalogue]
catalogue.vishnuv8.shop

[mongodb]
mongodb.vishnuv8.shop

[cart]
cart.vishnuv8.shop

[user]
user.vishnuv8.shop

[redis]
redis.vishnuv8.shop

[mysql]
mysql.vishnuv8.shop

[rabbitmq]
rabbitmq.vishnuv8.shop

[shipping]
shipping.vishnuv8.shop

[payment]
payment.vishnuv8.shop

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[local]
localhost