- name: python-setup
  include_roles:
    name: common
    tasks_from: python.yaml

- name: app-setup
  include_roles:
    name: common
    tasks_from: app-setup.yaml

- name: Systemd setup
  include_roles:
    name: common
    tasks_from: systemd.yaml