
- name: Install MySQL Server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: enable and start mysql service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes
  
- name: setup root passwd
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1