
- name: Install MySQL Server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: enable and start mysql service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes
  
- name: install boto3 and botocore
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - botocore
  - boto3
    
- name: setup root passwd
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{ MYSQL_ROOT_PASSWORD }}