- name: nodejs setup
  include_role:
    name: common
    tasks_from: nodejs.yaml

- name: appsetup
  include_role: 
    name: common
    tasks_from: app-setup
  
- name: Install mongodb repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install Mongodb client server
  ansible.builtin.dnf: 
    name: mongodb-mongosh
    state: present

- name: check products loaded or not
  ansible.builtin.command: mongosh --host mongodb.vishnuv8.shop --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output

- name: print catalogue_output
  ansible.builtin.debug:
    msg: "{{ catalogue_output}}"

- name: load master data
  ansible.builtin.shell: mongosh --host mongodb.vishnuv8.shop < /app/db/master-data.js
  when: catalogue_output.stdout | int < 0

- name: system setup
  include_role:
    name: common
    tasks_from: systemd.yaml