- name: create roboshop system user
  ansible.builtin.user:
    name: roboshop
    shell: /sbin/nologin
    system: true
    home: /app

- name: create app dir
  ansible.builtin.file: 
    path: /app
    state: directory

- name: download catalogue code
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
    dest: /tmp/catalogue.zip

# this thinks file is exist in ansible control server
# so we need to use remote_src: yes means files already exist in catalogue server  
- name: Extract catalogue code
  ansible.builtin.unarchive:
    src: /tmp/catalogue.zip
    dest: /app
    remote_src: yes