- name: install python3 packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
  - python3
  - gcc
  - python-devel

- name: Install Requirements
  ansible.builtin.pip:
    Requirements: requirements.txt
    executable: pip3.9
  args:
    chdir:  /app